version: '3.8'

services:
  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - speedroom-network

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - NODE_ENV=development
      - ADMIN_USERNAME=speedroom_admin
      - ADMIN_PASSWORD_HASH=$2b$10$4D0AbrWw/voC6ds4PmsxwOLfZHjwuV53R6Vh7Qaz4xnlfZH5rAGdq
      - SESSION_SECRET=speedroom-docker-secret
      - FRONTEND_URL=http://localhost:5173
      - ALLOWED_ORIGINS=http://localhost:5173,http://frontend:5173
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - speedroom-network

  # Redis (para produção com múltiplas instâncias)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - speedroom-network
    profiles:
      - production

  # Nginx (para produção)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - speedroom-network
    profiles:
      - production

volumes:
  redis_data:

networks:
  speedroom-network:
    driver: bridge